apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: workload-variant-autoscaler-vllm-mon
  labels:
    llm-d.ai/model: Qwen3-32B
spec:
  namespaceSelector:
    matchNames:
      - llm-d-optimized-baseline
  selector:
    matchLabels:
      llm-d.ai/model: Qwen3-32B
  endpoints:
    - port: vllm
      path: /metrics
      scheme: http
      interval: 15s
